### ISSUE TITLE
Crash when starting Rocksmith after following the guide

### ISSUE THREAD

**Issue by LegitGreenBoi** [theNizo/linux_rocksmith#15]
* EndeavourOS (Fully up to date, LTS Kernel, proprietary NVIDIA drivers)
* Proton 7.0-3
* Pipewire

* What appears to be the problem?
When following the arch-pipewire-new guide, after running the commands to launch the game, Rocksmith will open and crash either immediately or a few seconds into loading. Terminal includes these lines which seem to be related to the crash:
Attempting to load original DLL from: C:\windows\system32\avrt.dll
Load OK; fetching procedure addresses...
01bc:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Pro Audio",2821FF2C): stub
01c0:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Pro Audio",2887FE90): stub
wine: Unhandled page fault on execute access to 751EEF48 at address 751EEF48 (thread 0024), starting debugger...
Unhandled exception: page fault on execute access to 0x751eef48 in 32-bit code (0x751eef48).

* Did you notice any other unexpected behavior?
I don't believe so

* What did you try already?
I deleted and redid the prefix step but the crash still persists
I also tried disabling avrt.dll and that seemed to fix it, however this is an RSASIO file which is required for this setup.

I'd be happy to provide more info if needed, this seems to be related to RSASIO, mainly the avrt.dll file, I'm not 100% sure though.

**Comment by theNizo** [comment]
page faults are nasty.
Until the exception line (the last one you gave me), the terminal output is fine btw. Also judging by that, your RS_ASIO.ini config is probably correct, since it finds devices.
So as far as I can see, the audio devices are found and initiated and then the game can't handle something after that step. I don't know (yet) what that is though.

I've got a few loose ideas, nothing definitive though:

* First off, I noticed that the command `sudo groupadd realtime` had a typo in it. This _could_ be an issue.
* The last tip in the guide was to take the focus away from the game's window as soon as possible, until you hear sound. Did you try that?
* Leave the RS_ASIO files in the games directory. If you delete/rename the prefix, then immediately start the game (= create a new, unmodified prefix), does the game run? (it usually does for me, without sound)
* Do you have the Steam version of the game, or a different one?
* Did you verify the integrity of the game files? (In Steam, you can usually do this in Properties -> Local Files)
* Does rebuilding wineasio make any difference?

**Comment by LegitGreenBoi** [comment]
Thanks for the detailed reply,

I just tried the game again and it works now. I have no idea what changed but it all just works now.

Maybe a restart fixed it? Although I restarted the first time I tried it and it crashed so I'm not sure.

Anyways, I think it's safe for me to close this issue now that it's working.

Thanks for making such a nice guide :)
