### ISSUE TITLE
"Please Make Sure Steam is Running to Launch the Game" Error while starting Lutris

### ISSUE THREAD

**Issue by ShiroyukiX** [theNizo/linux_rocksmith#19]
-  ArchLinux (Manjaro on desktop rig)
-  Proton-GE 7.33, wine-staging (originally used GE-7.20 for the longest time)
- no pipewire. I use pulseaudio

This method use to work with no issues for at least half a year; however, as recent as this post date, I have been having issues getting Rocksmith2014 to work with CDLC and official DLC; this has occurring for about 3 days.

I have followed the aforementioned steps for non-pipewire method multiple times to get the same error: `Please make sure steam is running to launch the game`. The game does pick up my audio interface (Focusrite Scarlett Solo 2nd Gen) and I can play songs with no issue. The problem is my DLC and CDLC do not appear while launching with Lutris; launching with Steam gives the audio error it normally does, but my DLC and CDLC appear. Steam is running the whole time, just to clarify

I have tested this on both my normal Manjaro desktop and my newly installed Archlinux laptop; the issue appears on both. Something else I noticed is Lutris can launch the game even if Steam isn't running. This never happened previously, always giving a message about `unable to initialize Steam API` or something.

Not sure if an update to a package or a recent change in Steam is the cause, but I would like to figure out the problem quickly and get back to playing.

**Comment by theNizo** [comment]
(C)DLC usually don't appear if you forget to set a working directory (root folder of the game).

> I have followed the aforementioned steps for non-pipewire method multiple times to get the same error: `Please make sure steam is running to launch the game`

Either I don't quite understand what you wanted to say here, or this error is new. I haven't played the game in a while. I'll get back to you on this.

**Comment by theNizo** [comment]
Okay, so that's new.

The error message itself doesn't bother with starting the game, however, my save is only loaded if I start the game from Steam.

The `drive_c/Program Files (x86)/Steam/userdata` doesn't exist in the prefix anymore. I tried symlinking it from $HOME/.local/share/Steam/userdata`, but didn't suceed with getting my saves.

**Comment by theNizo** [comment]
Okay, yes, I figured out the issue, but not the workaround yet.

The game can't find Steam, but for some reason still starts.
The savefiles are probably handled different now. Using an older Proton version (Official 6.3 in my case) doesn't make a difference.
Because the game can't find Steam, it can't verify whether you own the DLCs, therefore they don't show up. This can be proven by cracking the game.

So what we need to figure out here is either how to get the wineasio stuff working when starting the game via Steam, or how to make the game detect Steam again..

**Comment by ShiroyukiX** [comment]
> Okay, yes, I figured out the issue, but not the workaround yet.
> 
>     * The game can't find Steam, but for some reason still starts.
> 
>     * The savefiles are probably handled different now. Using an older Proton version (Official 6.3 in my case) doesn't make a difference. If you create a new savefile, it appears in the root of the game's directory..
> 
>     * Because the game can't find Steam, it can't verify whether you own the DLCs, therefore they don't show up. This can be proven by cracking the game.
> 
> 
> So what we need to figure out here is either how to get the wineasio stuff working when starting the game via Steam, or how to make the game detect Steam again..

*Really wish github updated me that this issue was being worked on*

I was hoping it was user error on my part or some update to my linux system; looks like this isn't case. From what I could find online, it may have something to do with a new update they released for the game.
https://www.reddit.com/r/rocksmith/comments/xa49mq/important_update_coming_to_rocksmith_2014/

Maybe that plays a role into the game not finding the save files?

**Comment by yekteniya** [comment]
Confirming I am having this same issue since updating the game (and rsmods, rsasio and the .dll file). Same thing you're describing, with the save file only loading when the game is ran from Steam and therefore messing up the previous way of getting wineasio to work. 

Might consider reverting all the changes and going back to the beta branch JustInCaseWeNeedIt for the time being...

**Comment by theNizo** [comment]
> Might consider reverting all the changes and going back to the beta branch JustInCaseWeNeedIt for the time being...

That's probably what I'll recommend until someone comes up with a better solution.

**Comment by ShiroyukiX** [comment]
Switching to the beta branch, everything does work as usual... at least at first.

I now have problems with the game not picking up my output audio source and my jack input (Focusrite Scarlett Solo Gen 2). This occurs regardless if I start/stop `jack2`, open the game with lutris/steam or use a clean compatdata.

This is probably an issue on my end, given some other problems I've been experiencing with wine on both computers, as well as the default behavior for my main PC (Manjaro) acting up. However, I'll state it here just in case anyone else experiences the same thing.

**Comment by yekteniya** [comment]
Everything went back to working as usual in my case after switching to the temporary beta branch. 

@ShiroyukiX every setup is different but in my case whenever I get the no audio source detected warnings it's usually:
- Steam's Proton got updated and I have to copy the wineasio.dll to the library folders again
- Having to add the DLL to the registry of the wineprefix
- Wrong settings in the RS_Asio.ini file (this time for example had to restore the backup I had after reverting to the previous version)

**Comment by aaw3** [comment]
Can confirm this is still an issue. I had tried through both the terminal and lutris and was unable to access saves and had to relogin with ubisoft. I reverted to the previous version with the beta code but now do not have access to the CLDC content as it says "You must enable Steam Community In-Game to access the Shop."

**Comment by theNizo** [comment]
> Can confirm this is still an issue.

i mean, it's not marked as resolved either, but thanks i guess.

> now do not have access to the CLDC content

Forgot to `cd` first? Not enough information to confirm whether it is related.

**Comment by aaw3** [comment]
> > now do not have access to the CLDC content
> 
> Forgot to `cd` first? Not enough information to confirm whether it is related.

Yes, my bad. I overlooked the part of the guide where you have to cd into the game's working directory and the CDLCs has reappeared.

Both lutris and the terminal method are working now, I believe the steam running issue was happening only when I didn't have the beta_version properly set in the settings? Now that I set it back both are working now besides the in-game shop which I assume is because I am launching the game outside of the official steam launcher, so that doesn't really matter.

Thank you for your help!

**Comment by ShiroyukiX** [comment]
It's been a while since I came back to this; here's a an update:

The beta version does still work and recognizes my saves, as well as cdlc. The only issue I have now is finding the dll file on customforge, as it appears they put everything into a all-in-one installer now, which is separate from this.

I can call this issue fix. Just took me a while to get back here due to other priorities.

Hopefully a true fix will be implemented before the beta version disappears.

**Comment by theNizo** [comment]
Update, we don't need the beta workaround anymore!

**Comment by yekteniya** [comment]
This is great news, can confirm the non-pipewire debian method is working.

Heads up to anyone currently using wine-staging version 8.3: registering wineasio.dll will not work. Reverting to version 8.2 fixes the [issue](https://github.com/wineasio/wineasio/issues/24#issuecomment-1459183213)

**Comment by theNizo** [comment]
> wine-staging version 8.3: registering wineasio.dll will not work

Worked fine two days ago on my machine (Arch)... Interesting

**Comment by theNizo** [comment]
>registering wineasio.dll will not work.

Oh wait, I just had this issue (and resolved it): https://github.com/theNizo/linux_rocksmith/issues/28

**Comment by yekteniya** [comment]
> Oh wait, I just had this issue (and resolved it): #28

Thanks for the heads up! Registering it through Proton's wine did fix it for me. Glad that I can unhold the wine package now
