### ISSUE TITLE
Wineasio copy commands not working

### ISSUE THREAD

**Issue by Replicatorz** [theNizo/linux_rocksmith#2]
`# add to Proton version !! watch out for variables !!
cp /usr/lib32/wine/i386-windows/wineasio.dll "$PROTON/lib/wine/i386-windows/wineasio.dll"
cp /usr/lib32/wine/i386-unix/wineasio.dll.so "$PROTON/lib/wine/i386-unix/wineasio.dll.so"
cp /usr/lib/wine/x86_64-windows/wineasio.dll "$PROTON/lib64/wine/x86_64-windows/wineasio.dll"
cp /usr/lib/wine/x86_64-unix/wineasio.dll.so "$PROTON/lib64/wine/x86_64-unix/wineasio.dll.so"`

The first 2 commands told me no such file or directory exists, the last 2 said

"cp: '/usr/lib/wine/x86_64-unix/wineasio.dll.so' and '/lib64/wine/x86_64-unix/wineasio.dll.so' are the same file"

**Comment by theNizo** [comment]
So you said you're on an arch-based distro. AFAIK you also told me that you installed the AUR package `wineasio`. Which would also fit the commands.
I just installed the AUR package too, and the paths match on my system.

> The first 2 commands told me no such file or directory exists

I have no idea what happened here, other than maybe it didn't install correctly...

Could you please give me the outputs of the following commands:

	find /usr/lib/ -name "wineasio.dll"
	find /usr/lib/ -name "wineasio.dll.so"
	find /usr/lib32/ -name "wineasio.dll"
	find /usr/lib32/ -name "wineasio.dll.so"

> "cp: '/usr/lib/wine/x86_64-unix/wineasio.dll.so' and '/lib64/wine/x86_64-unix/wineasio.dll.so' are the same file"

You didn't assign or replace `$PROTON`, which is what I warned about just above.

Either adjust the commands, eg:

cp /usr/lib/wine/x86_64-windows/wineasio.dll "$HOME/.local/share/Steam/steamapps/common/Proton 7.0/dist/lib64/wine/x86_64-windows/wineasio.dll"

Or set the variable, eg:
	PROTON="/home/john/.steam/steam/steamapps/common/Proton 7.0/dist" # this assigns a value to it
and then run the commads

(setting a variable like this is only local and temporary, meaning only available in the shell instance you entered it in.)

**Comment by Replicatorz** [comment]
I apologize, im pretty new to linux, i said i am not very linux savvy yet but i am learning. I will do those commands now.

**Comment by theNizo** [comment]
No worries ^^

Manjaro is based on Arch.

Oh, btw, since you got confused with yay, it will ask you which package, just say `1`. For the rest you can just click enter. This way you accept the defaults (none), which are totally fine for pretty much everything I've installed yet.

Installing `base-devel` will make your life much easier when using the AUR, or when compiling other stuff too.

**Comment by Replicatorz** [comment]
I came from opensuse as that was my go to distro for a long time but always went back to windows cause of gaming but i always liked linux, thanks to proton and vulkan i feel like now i can drop windows finally and go fully linux and just learn more and try to get the stuff i had working in windows to work in here and this is one of the biggest compatibility issues i had so far.

I got the commands to work, so the wineasio is now in the proton, but i put it in the proton - experimental package as there was no proton 7 or any number following it. I tried retracing my steps, but getting no where, i am probably missing something though. I get no sound at all and the pop up saying no audio device is connected or whatever. I am pretty sure i have all settings correct in cadence.

Does this tutorial work with rocksmith cable, or is this for using a microphone or something? I am using my rocksmith cable.

**Comment by theNizo** [comment]
> but i put it in the proton - experimental package

That is fine, as long as you use that

> Does this tutorial work with rocksmith cable, or is this for using a microphone or something?

I use the Rocksmith cable all the time, but it should work with both, since Rocksmith accepts microphone input as well.

> I tried retracing my steps, but getting no where, i am probably missing something though.

I would assume you installed the packages. You're probably in the `audio` and `realtime` groups (check by running `groups`).

You can verify if wineasio is installed correctly, if the 4 find commands i listed earlier output 4 paths (ignore the errors).

**The prefix/compatdata (`steamapps/campatdata/221680`) is a common source of error. Try deleting and settinng that up again. Especially since you originally didn't have the correct file installed before.**

Lastly, you're starting the game from a script or Lutris, don't you?

**Comment by Replicatorz** [comment]
No, not using a script or lutris but that might be the reason, I did everything else correctly. I did see that at the end of your instructions however it said game wouldn't run when it did run so I assumed I didn't need to do that.

**Comment by Replicatorz** [comment]
Got It!!!!! The latency isn't as bad as i thought it would be either, feels just like it did on windows. Thanks for doing this and for being there for linux users and hope more get's expanded to make it easier, though not really that hard unless you are very new to linux.

**Comment by Replicatorz** [comment]
Question, is there a way to make the script into a shortcut instead of always having to start from console?

**Comment by theNizo** [comment]
If you use Lutris, it can do that for you.
You can also add the script as a non-Steam game.

Otherwise, insert this into $HOME/.local/share/applications/rocksmith.desktop
(replace the "Exec" path)

	[Desktop Entry]
	Name=Rocksmith® 2014 - JACK
	Comment=Play this game on Steam
	Exec=/path/to/your/script.sh
	Icon=steam
	Terminal=true
	Type=Application
	Categories=Game;

You can probably do it all in a .desktop file, but I didn't manage to do it yet.

Here's something to read, if you're interested: https://wiki.archlinux.org/title/Desktop_entries

**Comment by theNizo** [comment]
I'm sorry, I posted without reloading. Yes, there is, see [here](https://github.com/theNizo/linux_rocksmith/issues/2#issuecomment-1072116650).
