### ISSUE TITLE
easier way to launch through steam

### ISSUE THREAD

**Issue by stralytic** [theNizo/linux_rocksmith#22]
In your guides you say the way to launch "without lutris" is:

`# cd is necessary for the Rocksmith.ini and the DLC folder
cd $STEAMLIBRARY/steamapps/common/Rocksmith2014
PIPEWIRE_LATENCY=256/48000 WINEPREFIX=$STEAMLIBRARY/steamapps/compatdata/221680/pfx $PROTON/bin/wine $STEAMLIBRARY/steamapps/common/Rocksmith2014/Rocksmith2014.exe`

However an easier way is to open the Rocksmith 2014 game properties in steam, and under launch options, add the following:
`PIPEWIRE_LATENCY=256/48000 %command%`

**Comment by theNizo** [comment]
Please list the following first, so this issue can be of use to me:

* Which distro du you use
* Which Proton version do you use
* Did you do any other steps than shown in the guide? Did you leave anything out?

Now it gets interesting, because everytime i tried this setup, starting the game from Steam would make wineasio not work - the game told me that there are no audio devices. I tried using the command to get console output and it suddenly worked.

The big question here is what you did different.

**Comment by stralytic** [comment]
I'm using arch linux, 2:GE.Proton7.37-1 from chaotic-aur, and wineasio 1.1.0-3 also from chaotic-aur.

I copied wineasio into my proton directories:

```
sudo cp lib32/wine/i386-unix/wineasio.dll.so share/steam/compatibilitytools.d/proton-ge-custom/files/lib/wine/i386-unix
sudo cp lib32/wine/i386-windows/wineasio.dll share/steam/compatibilitytools.d/proton-ge-custom/files/lib/wine/i386-windows
sudo cp lib/wine/x86_64-unix/wineasio.dll.so share/steam/compatibilitytools.d/proton-ge-custom/files/lib64/wine/x86_64-unix
sudo cp lib/wine/x86_64-windows/wineasio.dll share/steam/compatibilitytools.d/proton-ge-custom/files/lib64/wine/x86_64-windows
sudo cp lib32/wine/i386-windows/wineasio.dll share/steam/compatibilitytools.d/proton-ge-custom/files/share/default_pfx/drive_c/windows/system32
sudo cp lib/wine/x86_64-windows/wineasio.dll share/steam/compatibilitytools.d/proton-ge-custom/files/share/default_pfx/drive_c/windows/syswow64
```

and ran this to register the wineasio dll

```
WINEPREFIX=/home/michael/.steam/steam/steamapps/compatdata/221680/pfx regsvr32 /usr/lib32/wine/i386-windows/wineasio.dll
```

Everything else was the same as your guide, except the final step of how to launch rocksmith2014.exe

**Comment by theNizo** [comment]
So, my theory about which system it's built on is probably wrong. I compiled [this](https://github.com/ValveSoftware/Proton/) (ver. 7.0) and it didn't work.

(Keep in mind that I don't know much about debugging wine. All I'm doing is guesswork.)

**Comment by cyrilpicard** [comment]
> So there's a difference between those versions. I don't know what it is yet, but my first guess would be that it was built on an arch machine instead of a [insert distro here]?

I am not sure, but my guess is that the difference with proton GE from AUR (and therefore Chaotic AUR) is that it uses system library instead of Steam runtime ones (the PKGBUILD has a dependency to steam-native-runtime and the configure.sh uses a flag --steam-runtime=native).

I was able to run the game from Steam with Proton Experimental with working wineasio using the following command to use system libjack :
LD_PRELOAD=/usr/lib32/libjack.so PIPEWIRE_LATENCY=256/48000 %command%

On my system (Arch Linux), with pipewire 0.3.67, the game crashed systematically at startup, but using the alt-tab trick I have managed to (randomly) run it.

With pipewire 0.3.68, the game starts without crashing, BUT nothing is wired to Rocksmith in the patchbay, so there is no sound in/output. I have to manually wire things after the game has started (I use Helvum). I have tried to automate the wiring with scripting, but it works only if there is another window in front of the game, otherwise the game crashes when the script is run.

**Comment by theNizo** [comment]
> I was able to run the game from Steam with Proton Experimental with working wineasio using the following command to use system libjack :

Worked on my machine.
Wanted to make sure and test further.
Redid my setup.
Nothing works now.
(Not the method's fault)
Will report back.

**Comment by theNizo** [comment]
Alright, so prefixes generated by Steam (when starting a game) all come broken on my machine at the moment (https://github.com/theNizo/linux_rocksmith/issues/28). I can't test this currently.

**Comment by theNizo** [comment]
> (#28)

Okay, that's done.

---

`LD_PRELOAD` technically works. You have to do the Alt-Tab trick only the first few times you boot the game up.
The disadvantage that I see to the current method is that you have to connect input and output by hand in the JACK patchbay, instead of having it work out of the box. Saves you from setting up the audio devices a certain way though...

Don't wire all connections in the patchbay at once. Do one, window focus on Rocksmith, do the second one, window focus on Rocksmith, and so on.

I would opt to list both options (`LD_PRELOAD` and [the one that's currently in the guide](https://github.com/theNizo/linux_rocksmith/issues/27)) and let the reader choose. They don't seem to break each other.

**Comment by cyrilpicard** [comment]
> The disadvantage that I see to the current method is that you have to connect input and output by hand in the JACK patchbay

I use a workaround to do this automatically, I use the following launch command, it is ugly, but it works :
`LD_PRELOAD="/usr/lib32/libjack.so" PIPEWIRE_LATENCY="256/48000" %command% & sleep 5; zenity --progress --title="PipeWire" --text="Configuring..." --percentage=100 & pid=$!; sleep 0.5; pw-link "alsa_input.usb-Hercules_Rocksmith_USB_Guitar_Adapter-00.mono-fallback:capture_MONO" "Rocksmith2014:in_1"; pw-link "Rocksmith2014:out_1" "alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo:playback_FL"; pw-link "Rocksmith2014:out_2" "alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo:playback_FR"; kill $pid`

The device names in the pw-link command must be adapted, they can be listed with
`pw-link -io`
Maybe the sleep timer must be adapted too.
The zenity window does nothing, but being here prevent the game from crashing.

**Comment by theNizo** [comment]
> I use a workaround to do this automatically

Line breaks make it quite easy to see what's going on here. Actually quite alright.

I was about to add this to the guide, but this is pipewire-specific. That will probably have to wait until I figure out the equivalent commands.

**Comment by cyrilpicard** [comment]
I think `jack_connect` should work (it requires jack-example-tools to be installed on Arch).
See https://github.com/tilk/run_rocksmith_linux/blob/master/run_rocksmith.sh to have an example of use.
