### ISSUE TITLE
Steam Deck & Garuda Issue

### ISSUE THREAD

**Issue by somekindahate** [theNizo/linux_rocksmith#25]
Hi,

I have tried out this guide on two different systems (steam & a Garuda Linux PC), and have run into the same problem with both of them.

The issue occurs when I try to install wineasio through the given steps. It reads and looks something like this:

>      rm -rf build32
>      rm -rf build64
>      make 32
>      make 64
>
>      make build ARCH=i386 M=32
>      make[1]: Entering directory '/home/scythe/Downloads/wineasio-1.1.0'
>      make[1]: *** No rule to make target 'rtaudio/include/asio.h', needed by 'build'.  Stop.
>      make[1]: Leaving directory '/home/scythe/Downloads/wineasio-1.1.0'
>      make: *** [Makefile:15: 32] Error 2
>      make build ARCH=x86_64 M=64
>      make[1]: Entering directory '/home/scythe/Downloads/wineasio-1.1.0'
>      make[1]: *** No rule to make target 'rtaudio/include/asio.h', needed by 'build'.  Stop.
>      make[1]: Leaving directory '/home/scythe/Downloads/wineasio-1.1.0'
>      make: *** [Makefile:18: 64] Error 2

![image](https://user-images.githubusercontent.com/81982464/209722879-bc32e86f-5f4d-4954-884e-be28a99f0aaa.png)

I also tried to run the shellscript provided and got this:

>      groupadd: group 'audio' already exists
>      groupadd: group 'realtime' already exists
>      cp: cannot stat '/usr/lib32/wine/i386-windows/wineasio.dll': No such file or directory
>      cp: cannot stat '/usr/lib32/wine/i386-unix/wineasio.dll.so': No such file or directory
>      cp: cannot stat '/usr/lib/wine/x86_64-windows/wineasio.dll': No such file or directory
>      cp: cannot stat '/usr/lib/wine/x86_64-unix/wineasio.dll.so': No such file or directory

I installed wine-staging and uninstalled regular wine prior to all of this based on the guide's suggestion. Please help. There seems to be what should be an obvious step missing that Linux novices like me are missing.

**Comment by theNizo** [comment]
### System

Both Arch-based with pipewire

### Script

(The script tells you that it's not compatible with pipewire. Maybe I should display this at a better location. Now this didn't destroy your audio setup, it just installed `jack2` instead of `pipewire-jack` - which would still work, can confirm, but I mean why if you already have pipewire?)

Anyway, the script installs `wineasio` via AUR, as a package. It should show up if you run `pacman -Q wineasio`

If it does, the `cp` errors would be strange indeed.

---

### Compile by hand

I can tell that you have downloaded and extracted the correct zip.

A quick search tells me this either happens if there's an error in the makefile or the file to be compiled doesn't exist.

Did you mess with these at all?

**Comment by somekindahate** [comment]
I did not mess with them at all. I only followed the steps as detailed.

**Comment by theNizo** [comment]
Okay, that's weird then. I tried this after reading your issue the first time, but worked just fine for me.

I'm afraid I don't have much advice to you, I'm sorry. The only thing I could think about is unlikely, because the output would be different, but I'll share regardless.

wineasio compilation depends on wine. Maybe something jack-related too (Too much dependencies on my system to test this, sorry). You could be missing a package, but then again it would result in a different terminal output.

<details><summary>Other thought that's probably not the issue, but I'll leave it here</summary>
Since you tried this on two different systems, I assume you downloaded it two times too. So I don't think there could have been corrupted while downloading (also, unlikely to happen exactly like this).
</details>

**Comment by NikhilSaini38** [comment]
Looks like gcc has changed something and won't build `asio.h` target unless explicitly directed to in `build` script
Ref:`make[1]: *** No rule to make target 'rtaudio/include/asio.h', needed by 'build'.`

**Comment by Siarkowy** [comment]
> Ref:`make[1]: *** No rule to make target 'rtaudio/include/asio.h', needed by 'build'.`

I think I hit the same problem when compiling on Steam Deck.

You need to initialize git submodules in existing wineasio repository because they are empty by default.

```
git submodule update --init --recursive
```

Or do a fresh clone including submodules.

```
git clone --recursive https://github.com/wineasio/wineasio.git
```

**Comment by theNizo** [comment]
1st, what @Siarkowy wrote works on my machine
2nd, did you clone it, or download the .tar.gz from the releases page?

**Comment by theNizo** [comment]
For Steam Deck you cloned, obviously, because you use a modified version of wineasio. I forgot.

I would opt for the second option and adjust the guide accordingly, but I have the question if you still need that modified version of wineasio.
