### ISSUE TITLE
Addition to Arch Pipewire script 

### ISSUE THREAD

**Issue by TheAndroidx1** [theNizo/linux_rocksmith#62]
As stated in the guide pavucontrol needs to be open when launching the script otherwise it will crash, but I found it annoying to have to open pavucontrol and launch the script, then finish playing and close pavucontrol.

A simple addition of 

`pavucontrol &
sleep 2
`

would open pavucontrol then launch the game, and after the game is closed it would automatically close pavucontrol!

Thanks for the guide! allowed me to finally make the jump to arch from windows!

**Comment by theNizo** [comment]
Hi!

If I were to do it like you wrote here, that line would be added in the "generate launch script" sub-guides. These are the same for both pipewire-jack and native JACK, but what you recommend would only be needed for pipewire-jack. Therefore, I would not be that happy to make it a default thing.

What would you think about putting it [here](https://github.com/theNizo/linux_rocksmith/blob/main/guides/which-guide-should-i-choose.md#i-just-want-to-click-one-button-and-expect-the-thing-to-work-pretty-much-all-the-time)? (Into the last question)

Note to self, I'd also want to try what exactly happens if pavucontrol is already opened, just to be sure.

**Comment by theNizo** [comment]
... Hello?

I'd like to hear another opinion too.

If I don't, I'll just do what I suggested.

**Comment by theNizo** [comment]
Done 0456b69

If you want it different, you can still write here.
