### ISSUE TITLE
enable steam in lutris

### ISSUE THREAD

**Issue by shoe-strap** [theNizo/linux_rocksmith#7]
setting environment variable LUTRIS_ENABLE_PROTON to have the value 1 before starting Lutris works a lot better than manually linking Proton installations as runners. With this set, Lutris will detect all installed Proton branches other than Experimental as valid runners.

**Comment by theNizo** [comment]
Good thing to know, but this certainly doesn't seem to work with GE-Proton versions...

The problem I have with it is that running Proton via Lutris (without it's wrapper) is openly discouraged.

You have given me a different idea though. You can select "Custom" as the runner and point to `stuff/basically/bin/wine`. This is an idea, because less commands, more gui. I'll think about it and get back when I'm done [testing pipewire](https://github.com/theNizo/linux_rocksmith/issues/1#issuecomment-1111051000).

**Comment by theNizo** [comment]
I've put in instructions for "Custom" now.

When thinking about where I could put this info, I wouldn't know where.

If there's nothing else you want to add, I'll close this issue in 2 days.
